### ISSUE TITLE
is alias supported?

### ISSUE THREAD

**Issue by sergii-sakharov** [mvisonneau/puppet-curator#7]
Alias has slightly different def to other actions:

```
action: alias
description: "Add/Remove selected indices to or from the specified alias"
options:
  name: alias_name
add:
  filters:
  - filtertype: ...
remove:
  filters:
  - filtertype: ...
```

Specifically filters are inside add or remove which does not seem to be supported by action.pp (unless I'm missing sth here)

Here's the sample config:
```
      7:
        action: alias
        description: Recreate alias for combined *logstable indices
        options:
          name: logstable_combo
        remove:
          filters:
            - filtertype: none
        add:
          filters:
            - filtertype: pattern
              kind: regex
              value: '.*logstable-.*$'
```
